title: Hanweeee Blog
author: hanweeeelee
email: mobiledev@kakao.com
description: > # this means to ignore newlines until "show_exerpts:"
  안녕하세요. 이한위 블로그입니다.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
url: "https://hanweeeelee.github.io/"


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Hanweeee Blog
  tagline: iOS / macOS Application Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
#    twitter: "https://www.naver.com"
    github:  hanweeeelee
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
